spring.application.name=trainingmanagement
# ===== Application Info =====
spring.application.name=trainingmanagement

# ===== Server =====
server.port=8080

# ===== PostgreSQL Datasource =====
spring.datasource.url=jdbc:postgresql://localhost:5432/training_management
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:rachitha123}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
